### PR TITLE
Feature/issue 44 bson factory copy method support

### PR DESCRIPTION
**Pull request by datalorax**
#44 Resolved - added support for copy() method on BsonFactory to allow cloning of ObjectMappers using BsonFactory instances.

### CODE REVIEW

**Comment by datalorax** [comment]
I see this is some kind of backwards compatibility issue. I'll take a look.

**Comment by michel-kraemer** [comment]
Thank you so much for the PR. I have some minor nitpicks. If you can fix them I will happily merge the PR.

Thanks,
Michel

**Comment by datalorax** [comment]
All done, I think :D

**Comment by michel-kraemer** [comment]
Thanks again for the contribution. I will try to fix #46 and then I can release a new version.

Cheers,
Michel

**Comment by datalorax** [comment]
No worries. Happy to help.  I look forward to the new version :)

**Pull request merged**
