### PR TITLE
Improve serialization performance by using bulk api for binary type.

### LINKED ISSUE #97: Serialization performance with large objects
Hi,
We are using bson4Jackson to serialize outbound messages from our server to clients in BSON format. 
We have observed that in case of large messages, bson4Jackson is taking time to serialize the object which is resulting in a bit of lag in our responses. 
For instance, it takes approximately 300-400ms to serialize a message with size 23 MB.
Our outbound messages are responses to paged requests and as the client increases the page size , the serialization time  becomes even more significant. 
On further profiling this, we found that the **BsonGenerator#writeBinary(Base64Variant b64variant, byte subType, byte[] data, int offset, int len)** is the class method where most of the time is spent.
It uses a heap based byte buffer and copies the message byte by byte into it.
`while (offset < end) {
            _buffer.putByte(data[offset]);
            ++offset;
        }`
		
Any suggestions through which we can improve the serialization performance or any existing configuration that might be of help? Also, is it possible to skip the serialization of a field but still include it in the final output? We do have some fields in the outbound message that are BSON serialized. Can we use them as is in the serialization output of outbound message via  some annotation/property ?

This is how we are creating the ObjectMapper:
`BsonFactory bsonFactory = new BsonFactory();
bsonFactory.enable(BsonGenerator.Feature.WRITE_BIGDECIMALS_AS_STRINGS);       
ObjectMapper mapper = new ObjectMapper(bsonFactory);`

This is how we are serializing the object:
`ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
mapper.writeValue(byteArrayOutputStream, object);		//this object is roughly 23MB`

Bson4Jackson version we are using: 2.9.2

Thanks for your help in advance.

### PR DESCRIPTION
**Pull request by a-narsudinov**
Hi, I wanted to use this library in one of my projects and had had same problem as desribed in #97.

This patch contains my naive implementation of bulk api for binary types.

My simple tests show that large documents serialization now much faster (up to 10 times).

I'm not sure about new public api method in `DynamicOutputBuffer` I've added, should it stays like this?

P.S. Thanks for a great project! :^)

Fixes #97

### CODE REVIEW

**Comment by a-narsudinov** [comment]
@michel-kraemer could you have a look, please?

**Comment by RY0502** [comment]
Hi Michel,
Are you planning to merge this in the next/future version? Any timelines for it ?

**Comment by michel-kraemer** [comment]
Sorry for the late response. I just merged the pull request. Thank you very much for your support!

I will release a new version later today.

**Comment by michel-kraemer** [comment]
@a-narsudinov Very good work, by the way!

**Pull request merged**
