### PR TITLE
add explicit support for Jackson 2.6.x version

### PR DESCRIPTION
**Pull request by atoulme**
I ran tests locally (using gradle clean install ?) and everything passes.

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the PR. bson4jackson 2.5 runs well with Jackson 2.6. Why should we release a new version? Have you experienced a specific issue?

**Comment by atoulme** [comment]
I have not, I guess I got confused with the README. I'll amend the PR.

**Comment by dadoonet** [comment]
+1

**Comment by michel-kraemer** [comment]
I'm currently working on a fix for #51. After this I will release a new version. I'll call it 2.6 to be in line with Jackson again.

Cheers,
Michel

**Pull request merged**
